### ISSUE TITLE
Multiple file views don't trigger inactive panes correctly

### ISSUE THREAD

**Issue by foxx** [SublimeText/InactivePanes#13]
Steps to reproduce;

* Create two panes
* Open any file
* Open the same file again once using "New View into File"
* Drag the second view into the second pane
* Notice that inactive panes does not show either pane as active (see screenshot)

![screen shot 2015-08-21 at 16 18 07](https://cloud.githubusercontent.com/assets/651797/9411814/39f723ca-4820-11e5-8b86-5255f1cf40e9.png)

**Comment by FichteFoll** [comment]
This is a known issue and cause by a bug in Sublime Text (https://github.com/SublimeTextIssues/Core/issues/731). Nothing I can do about.

It works properly after you restart ST.

**Comment by foxx** [comment]
May I recommend keeping this, or #10, open until upstream has been fixed? It's still a valid bug, regardless of fault.

**Comment by FichteFoll** [comment]
Is [this](https://github.com/SublimeText/InactivePanes#known-issues) not enough?
