### ISSUE TITLE
Multiple Instances of the same file breaks dimming

### ISSUE THREAD

**Issue by safield** [SublimeText/InactivePanes#18]
When the same file is opened in two different panes, all instances of that file are drawn dimmed.

To reproduce, split sublime into any configuration of multiple panes. Open file some_file in one of the panes. It will correctly draw as the active pane. In a different empty pane, open another instance of some_file. At this point, both the initial, and subsequent instances of some_file will be drawn inactive, regardless of if they are focused or not.

**Comment by adzenith** [comment]
This is listed in the known issues in the readme. There's no way around this using Sublime Text's API, unfortunately.

**Comment by FichteFoll** [comment]
As also mentioned in the Readme, restarting Sublime Text makes the two views act independently.
