### ISSUE TITLE
Incompatible with Monokai

### ISSUE THREAD

**Issue by yuyudhan** [SublimeText/InactivePanes#19]
I have monokai color sceme enabled. 
It gives following error message continuously, the warning message won't on clicking OK or cross and appears again and again.

> Warning!
> Your setup seems to use an unrecognized color scheme setting which InactivePanes does not take care of. Please create an issue at this package's repository or a post in the forum and mention your color_scheme path: 'Monokai.sublime-color-scheme'.

**Comment by FichteFoll** [comment]
The plugin hasn't been updated for the new scheme format yet.

**Comment by FichteFoll** [comment]
You can follow #17 for the progress.
