### ISSUE TITLE
error when loading InactivePanes theme file

### ISSUE THREAD

**Issue by safield** [SublimeText/InactivePanes#20]
Sublime text 3.2
Windows 10 1809

I just updated to Sublime Text version 3.2. Now I am getting sporadic errors that indicate and issue with the InactivePanes theme file.

InactivePanes seems to be functioning like normal, but the sporadic error dialogs are still and issue.

The only relevant writes in the log I could find are....

> error: Error loading colour scheme Packages/InactivePanes/Packages/User/safire_star.tmTheme: Unable to open Packages/InactivePanes/Packages/User/safire_star.tmTheme

I have attached the theme I am using.

[safire_star.zip](https://github.com/SublimeText/InactivePanes/files/2967498/safire_star.zip)

![sublime_inactivepanes_error](https://user-images.githubusercontent.com/12876404/54374958-28f44000-464e-11e9-8ea1-d37870cbac05.png)

**Comment by FichteFoll** [comment]
I suggest running the following line in the ST console and restarting ST to reset old references to theme files.

```py
[view.settings().erase('color_scheme') for window in sublime.windows() for view in window.views()]
```

**Comment by safield** [comment]
Ran that in console. I am still getting intermittent error dialogs popping up.

**Comment by safield** [comment]
Ran it on my Windows machine and the output was as follows (not sure what I should expecting).

> >>> [view.settings().erase('color_scheme') for window in sublime.windows() for view in window.views()]
> []

I can now get the error to happen reliably by opening the keyboard shortcuts window.

**Comment by FichteFoll** [comment]
By "keyboard shortcuts window" you mean *Preferences > Key Bindings*?

**Comment by safield** [comment]
Yes. For a brief period it was reliably reproducible this way. Unfortunately I was mistaken, and now it isn't reproducible this way. It is back to being completely unpredictable and sporadic :/

**Comment by kjteske** [comment]
I'm also seeing this issue, Sublime Text 3.2 on macOS. The error message appears sporadically for me as well.

**Comment by FichteFoll** [comment]
Just a heads-up: This issue is usually a nightmare to debug because it can be caused by a variety of things, including races. The best solution would be a rewrite and trying to use the cache directory that I then don't need to cleanup regularly, but see #17 for details.

I don't have the capacity currently to go through with this and other issues on other projects have higher priorities.

**Comment by FichteFoll** [comment]
The package has been deprecated and the functionality has been implemented natively into Sublime Text 4. Refer to the [readme](https://github.com/SublimeText/InactivePanes#readme) for instructions if you don't already use the new feature.
