### ISSUE TITLE
Switching projects results in dim files

### ISSUE THREAD

**Issue by safield** [SublimeText/InactivePanes#21]
SublimeText v 3.2
Windows 10 1809

I have two projects. In each project I have 1 file open, and the editor configured with only a single pane.

When I hit ctrl+alt+p to quick switch between projects, the file in the subsequently opened project is displayed dimmer than normal.

To Rectify this problem I have to refresh focus on the file by hitting ctrl+alt+p followed by esc key, or by opening another file, and then switching back to the original file.

When I uninstall InactivePanes plugin, this issue is not present.

Observer the screenshot displaying the normal view and the dimmed one.
![inactive_Panes_bug](https://user-images.githubusercontent.com/12876404/55517957-caf8be00-5637-11e9-9016-444d20c5b61d.jpg)

**Comment by FichteFoll** [comment]
The package has been deprecated and the functionality has been implemented natively into Sublime Text 4. Refer to the [readme](https://github.com/SublimeText/InactivePanes#readme) for instructions if you don't already use the new feature.
