### ISSUE TITLE
Incompatible with ColorHighlighter (notably when uninstalling) and GitSavvy

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/InactivePanes#9]
There is an issue (#8) where CH appears to pick up a dimmed scheme and caches it internally for continuous changes. I'm not sure if there is much that we can do here, but I should at least investigate into the source at some point.

**Comment by oddysee** [comment]
There's also a similar behaviour occuring when using [Inactive Panes](https://github.com/SublimeText/InactivePanes/) where the in-line diff no longer shows colours correctly.

**Comment by oddysee** [comment]
Another instance is when using [Origami](https://github.com/SublimeText/Origami/) and cloning a file to another pane. Both appear dimmed.

**Comment by FichteFoll** [comment]
Indeed, GitSavvy appears to be modifying the color scheme [as well](https://github.com/divmain/GitSavvy/blob/33bdf78e27f21ce4559b85d988eb357799249532/core/commands/inline_diff.py#L67-L101), even though it should technically only do so once for each theme (like SublimeLinter does).
I should probably start working on some API that would centralize temporary and permanent color scheme changes so that we don't have these conflicts anymore. Not any time soon though, I'm afraid. Maybe once I start using GitSavvy.

The second issue you are reporting is an upstream but in Sublime Text: https://github.com/SublimeText/InactivePanes/issues/13

**Comment by pradyunsg** [comment]
Marking a view as "dimmed" and then checking that flag when we go to dim it should help.

This flag can be reset on the visible views every time the active view is changed.

Does that sound good?

**Comment by FichteFoll** [comment]
@pradyunsg I'm not sure which kind of flag you are talking about?

**Comment by pradyunsg** [comment]
So... My idea is when a panel is dimmed, a setting key (say inactive_panes_dimmed) is set to true. If this key is true, re-dimming the view will do nothing.

If a view is undimmed, if the key is false, nothing is done. If it is true, it sets it to false and modifies the view.

Basically, keeping track of the last action of inactive panes on a view to determine the next action. 

(on a mobile)

**Comment by FichteFoll** [comment]
Unfortunately, this will still be subject to race conditions caused by other packages simultaneously modifying a color scheme and making a view-specific override. There needs to be a way to standardize color scheme modifications (both globally and locally) between different packages, otherwise this won't be solved.

**Comment by FichteFoll** [comment]
I am not interested in pursuing this. It's a very involved race condition that would need to be solved by a unified framework for scheme monkeypatching and I can only be achieved through cooperation from ColorHighlighter's side. Idk about GitSavvy.

ColorHelper is a much better plugin that uses new features in the form of phantoms and minihtml and does not rely on monkeypatching the color scheme.

**Comment by pradyunsg** [comment]
Thanks @FichteFoll! :)
